apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-frontend-app
  template:
    metadata:
      labels:
        app: my-frontend-app
    spec:
      containers:
        - name: my-frontend-app
          image: sample-app # Update this line with your Docker image
          ports:
            - containerPort: 80

